<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-A11EL1IC" ignored="0" name="Test" tests="8" failures="2" timestamp="2020-04-01T18:19:42 IST" time="0.113" errors="0">
  <testcase name="RetryTest1" time="0.014" classname="TestNGExamples.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest1 -->
  <testcase name="RetryTest1" time="0.002" classname="TestNGExamples.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest1 -->
  <testcase name="RetryTest1" time="0.005" classname="TestNGExamples.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest1 -->
  <testcase name="RetryTest1" time="0.001" classname="TestNGExamples.RetryLogic">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestNGExamples.RetryLogic.RetryTest1(RetryLogic.java:12)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RetryTest1 -->
  <testcase name="RetryTest2" time="0.004" classname="TestNGExamples.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest2 -->
  <testcase name="RetryTest2" time="0.001" classname="TestNGExamples.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest2 -->
  <testcase name="RetryTest2" time="0.002" classname="TestNGExamples.RetryLogic">
    <skipped/>
  </testcase> <!-- RetryTest2 -->
  <testcase name="RetryTest2" time="0.002" classname="TestNGExamples.RetryLogic">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at TestNGExamples.RetryLogic.RetryTest2(RetryLogic.java:18)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- RetryTest2 -->
</testsuite> <!-- Test -->
